# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 18:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=512, null=True)),
                ('icon', models.ImageField(default='/icons/icon.png', upload_to='')),
                ('create_time', models.DateField(default=datetime.datetime(2018, 2, 28, 18, 52, 7, 613271, tzinfo=utc))),
                ('moderator', models.BooleanField(default=False)),
                ('group_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=512)),
                ('icon', models.ImageField(default='/icons/icon.png', upload_to='')),
                ('group_id', models.IntegerField()),
            ],
        ),
    ]
